string = "abcdefg"

print(string[2 : 6])
print("===========")
print(string[ : 6])
print("===========")
print(string[ :: ])
print("===========")
print(string[5 : ])
print("===========")
print(string[::-1])
print("===========")
print(string[::1])
print("===========")
print(string[::2])
print("===========")
print(string[::-2])
print("===========")
print(string[::3])